name: cmdcraft unit testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, v*-rc]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install Dependencies
        run: |
          sudo apt remove python3-pip
          python -m pip install --upgrade pip
          python -m pip install . ruff coverage pytest readme_renderer
      - name: Analysis
        run: ./tools/analyse.sh
      - name: Tests
        run: ./tools/test.sh
      - name: Validate README.rst
        run: python -m readme_renderer README.rst